name: "Dynamic Matrix (Composite)"
description: "Splits a comma-separated string into a matrix"
author: "Casey Schadewitz"
inputs:
  matrix_input:
    description: "Matrix input (comma-separated)"
    required: true
    type: string

outputs:
  matrix:
    description: "Matrix output"
    value: ${{ steps.split_matrix.outputs.out }}

runs:
  using: "composite"
  steps:
    - id: split_matrix
      name: "Split matrix"
      shell: bash
      run: |
        input=${{ inputs.matrix_input }}
        echo "matrix=[\"${input//,/\",\"}\"]"
        echo "matrix=[\"${input//,/\",\"}\"]" >> $GITHUB_OUTPUT
        echo $GITHUB_OUTPUT
