name: ACRTESTSUBTASK

on:
  workflow_call:
    inputs:
      ACR_USERNAME:
        required: true
        type: string
    secrets:
      ACR_PASSWORD:
        required: true

env:
  ACR_USERNAME: ${{ inputs.ACR_USERNAME }}
  ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Print
        run: |
          echo ${{ env.ACR_USERNAME }}
  test:
    runs-on: ubuntu-latest
    container:
      image: githubtoacr.azurecr.io/ubuntu:latest
      credentials:
        username: ${{ env.ACR_USERNAME }}
        password: ${{ env.ACR_PASSWORD }}
    steps:
      - name: Test
        run: |
          echo "Hello World"