name: Bottom Level

on:
    workflow_call:
        inputs:
            name:
                description: 'Name of the person to greet'
                required: true
                default: 'Mona the Octocat'
                type: string

jobs:
    greet:
        continue-on-error: false
        runs-on: ubuntu-latest
        steps:
            - run: echo "Hello, ${{ inputs.name }}"

    should-fail:
        runs-on: ubuntu-latest
        if: ${{ inputs.name == '1' }}
        steps:
            - run: echo "This job should fail"
    
    status-check:
        runs-on: ubuntu-latest
        needs: [greet, should-fail]
        if: always()
        steps:
            - run: echo "${{ job.status }}"
              
