name: TestMatrixSplitAlternative

on:
  workflow_dispatch:
    inputs:
      matrix_input:
        description: 'Matrix input (comma-separated)'
        required: true
        default: 'Hello,World,This,Is,A,Test'
        type: string

jobs:
  setup_matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.setup_matrix.outputs.matrix }}
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.ref }}
      - name: list
        run: |
          pwd
          ls -la
      - id: setup_matrix
        uses: ./actions/dynamic-matrix
        with:
          matrix_input: ${{ github.event.inputs.matrix_input }}
  test_matrix:
    needs: setup_matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        word: ${{ fromJson(needs.setup_matrix.outputs.matrix) }}
    steps:
      - name: Test matrix
        run: echo ${{ matrix.word }}