name: TestMatrixSplitAlternative

on:
  workflow_dispatch:
    inputs:
      matrix_input:
        description: 'Matrix input (comma-separated)'
        required: true
        default: 'Hello,World,This,Is,A,Test'
        type: string

jobs:
  PrintString:
    runs-on: ubuntu-latest
    steps:
      - name: Print
        run: echo ${{ inputs.matrix_input }}
  PrintArray:
    runs-on: ubuntu-latest
    steps:
      - name: Print
        run: echo ${{ format('["{0}"]', inputs.matrix_input) }}
  TestArray:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        input: ${{ format('["{0}"]', inputs.matrix_input) }}
    steps:
      - name: Test
        run: echo ${{ matrix.input }}
  PrintMatrix:
    runs-on: ubuntu-latest
    steps:
      - name: Print
        run: echo ${{ fromJson(format('[{0}]', inputs.matrix_input)) }}
  TestMatrix:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        input: ${{ fromJson(format('[{0}]', inputs.matrix_input)) }}
    steps:
      - name: Test
        run: echo ${{ matrix.input }}