name: Mid Level

on:
    workflow_call:

jobs:
    start:
        runs-on: ubuntu-latest
        steps:
            - name: Start
              run: echo "Starting"
        
    matrix:
        uses: ./.github/workflows/bottom_level.yml
        strategy:
            matrix:
                name: ["1", "2", "3"]
            fail-fast: true
        with:
            name: ${{ matrix.name }}

    check:
        needs: matrix
        if: ${{ needs.matrix.result == 'failure' || needs.matrix.result == 'cancelled' }}
        runs-on: ubuntu-latest
        steps:
            - name: Check
              run: exit 1

    end:
        if: always()
        runs-on: ubuntu-latest
        needs: matrix
        steps:
            - name: End
              run: |
                echo "Matrix status: ${{ needs.matrix.result }}" >> $GITHUB_STEP_SUMMARY
                echo "job status: ${{ job.status }}" >> $GITHUB_STEP_SUMMARY