name: Top Level

on:
    workflow_dispatch:


jobs:
    reusable-workflow-job:
        uses: ./.github/workflows/mid_level.yml
    
    check-state:
        runs-on: ubuntu-latest
        needs: reusable-workflow-job
        steps:
            - name: Check state
              run: |
                echo "Reusable Job State: ${{ needs.reusable-workflow-job.result }}" >> $GITHUB_STEP_SUMMARY
                echo "job status: ${{ job.status }}" >> $GITHUB_STEP_SUMMARY
